language: haxe
haxe:
- 4.0.0-rc.5
services:
- xvfb
addons: 
env:
  global:
  - NEKOPATH=/usr/local/lib/neko:$TRAVIS_BUILD_DIR/test/build/neko/bin
stages:
- name: after_success
  if: branch = master AND env(TRAVIS_SECURE_ENV_VARS) = true
install:
- haxelib install lime --quiet
- haxelib install openfl --quiet
- haxelib install actuate --quiet
- haxelib install dox --quiet
- haxelib install munit --quiet
- haxelib dev feathersui . --quiet
- npm install
script:
# build js library
- npm run build
# build swc library
- haxelib run openfl build flash
# build documentation
- cd $TRAVIS_BUILD_DIR/docs
- haxe docs.hxml
# build components-explorer example
- cd $TRAVIS_BUILD_DIR/examples/components-explorer
- haxelib run openfl build neko
- haxelib run openfl build html5
- haxelib run openfl build flash
# run automated tests
- cd $TRAVIS_BUILD_DIR/test
- haxelib run munit test -neko -result-exit-code
after_success:
- ssh-keyscan -H feathersui.com >> ~/.ssh/known_hosts
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- chmod 600 /tmp/sftp_rsa
- scp -i /tmp/sftp_rsa -r $TRAVIS_BUILD_DIR/build/api dh_feathers@feathersui.com:~/api.feathersui.com/unstable