language: haxe

haxe:
- "4.0.0-rc.3"

services:
- xvfb

addons:
- chrome: stable

env:
- NEKOPATH=/usr/local/lib/neko:$TRAVIS_BUILD_DIR/test/build/neko/bin

install:
- haxelib install lime --quiet
- haxelib install openfl --quiet
- haxelib install actuate --quiet
- haxelib install dox --quiet
- haxelib install munit --quiet
- haxelib dev feathersui . --quiet

script:
# build docs
- cd $TRAVIS_BUILD_DIR/docs
- haxe docs.hxml

# build components-explorer example
- cd $TRAVIS_BUILD_DIR/examples/components-explorer
- haxelib run openfl build neko
- haxelib run openfl build html5
- haxelib run openfl build flash

# run tests
- cd $TRAVIS_BUILD_DIR/test
- haxelib run munit test -neko -result-exit-code
- haxelib run munit test -js -browser google-chrome-stable -result-exit-code
