language: haxe

haxe:
- "development"

install:
- haxelib install lime
- haxelib run lime setup
- haxelib install openfl
- haxelib run openfl setup
- haxelib install actuate
- haxelib dev feathersui .

script:
- cd docs
- haxe docs.hxml