language: haxe

haxe:
- "4.0.0-rc.3"

install:
- haxelib install lime --quiet
- haxelib run lime setup --quiet --always
- haxelib install openfl --quiet
- haxelib run openfl setup --quiet --always
- haxelib install actuate --quiet
- haxelib install dox --quiet
- haxelib dev feathersui . --quiet

script:
- cd docs
- haxe docs.hxml