language: haxe

haxe:
- "4.0.0-rc.3"

install:
- haxelib install lime --quiet
- haxelib install openfl --quiet
- haxelib install actuate --quiet
- haxelib install dox --quiet
- haxelib install munit --quiet
- haxelib dev feathersui . --quiet

script:
- cd docs
- haxe docs.hxml
- cd ../test
- haxelib run munit test -js -browser firefox -result-exit-code