language: haxe

haxe:
- "4.0.0-rc.3"

install:
- haxelib install lime --quiet
- haxelib install openfl --quiet
- haxelib install actuate --quiet
- haxelib install dox --quiet
- haxelib install munit --quiet
- haxelib dev feathersui . --quiet

before_script:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3; # give xvfb some time to start
  fi

script:
- cd docs
- haxe docs.hxml
- cd ../test
- haxelib run munit test -js -browser firefox -result-exit-code