language: haxe

haxe:
- "development"

install:
- haxelib git lime https://github.com/openfl/lime.git
- haxelib run lime setup
- haxelib git openfl https://github.com/openfl/openfl.git
- haxelib run openfl setup
- haxelib install actuate
- haxelib install dox
- haxelib dev feathersui .

script:
- cd docs
- haxe docs.hxml