name: API Reference

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install actuate --quiet
        haxelib install dox --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build API reference
      working-directory: docs
      run: haxe docs.hxml