name: CLI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Run CLI
      run: |
        haxelib run feathersui new-project MyProject
        cd MyProject
        haxelib run openfl build html5