name: Flash

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build Flash .swc library
      run: haxelib run openfl build flash -debug
    - uses: actions/upload-artifact@v3
      with:
        name: feathersui-openfl-swc
        path: bin/flash/bin/feathersui-openfl.swc
        if-no-files-found: error