name: Haxelib

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: feathersui-haxelib
        path: |
          src/
          tools/
          haxelib.json
          include.xml
          README.md
          LICENSE.md
          CHANGELOG.md
          CONTRIBUTING.md
        if-no-files-found: error