name: Samples

on:
  push:
  pull_request:
    branches:
      - master

jobs:

  build-misc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build samples/animated-tween-skin
      working-directory: samples/animated-tween-skin
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/calculator
      working-directory: samples/calculator
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/components-explorer
      working-directory: samples/components-explorer
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/custom-programmatic-skin
      working-directory: samples/custom-programmatic-skin
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/custom-programmatic-skin-with-states
      working-directory: samples/custom-programmatic-skin-with-states
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/custom-theme
      working-directory: samples/custom-theme
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/dark-mode
      working-directory: samples/dark-mode
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/hello-world
      working-directory: samples/hello-world
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/hn-reader
      working-directory: samples/hn-reader
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/horizontal-layout-percentage-sizing
      working-directory: samples/horizontal-layout-percentage-sizing
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/list-view-data-provider-collection-sorting
      working-directory: samples/list-view-data-provider-collection-sorting
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/login-form
      working-directory: samples/login-form
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/magic-8-ball-chat
      working-directory: samples/magic-8-ball-chat
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/router-navigator-pass-data-between-views
      working-directory: samples/router-navigator-pass-data-between-views
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/router-navigator-save-and-restore
      working-directory: samples/router-navigator-save-and-restore
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/stack-navigator-pass-data-between-views
      working-directory: samples/stack-navigator-pass-data-between-views
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/stack-navigator-save-and-restore
      working-directory: samples/stack-navigator-save-and-restore
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/tab-navigator
      working-directory: samples/tab-navigator
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl
    - name: Build samples/todomvc
      working-directory: samples/todomvc
      run: |
        haxelib run openfl build neko
        haxelib run openfl build html5
        haxelib run openfl build flash
        haxelib run openfl build hl

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib install hxcpp --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build samples/components-explorer
      working-directory: samples/components-explorer
      run: |
        haxelib run openfl build linux

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib install hxcpp --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build samples/components-explorer
      working-directory: samples/components-explorer
      run: |
        haxelib run openfl build mac

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib install hxcpp --quiet
        haxelib dev feathersui ${{ github.workspace }} 
    - name: Build samples/components-explorer
      working-directory: samples/components-explorer
      run: |
        haxelib run openfl build windows

  build-air:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: joshtynjala/setup-adobe-air-action@v2
      with:
        air-version: "33.1"
        accept-license: true
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install hxargs --quiet
        haxelib dev feathersui ${{ github.workspace }} 
        haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
    - name: Build samples/animated-tween-skin
      working-directory: samples/animated-tween-skin
      run: |
        haxelib run openfl build air
    - name: Build samples/calculator
      working-directory: samples/calculator
      run: |
        haxelib run openfl build air
    - name: Build samples/components-explorer
      working-directory: samples/components-explorer
      run: |
        haxelib run openfl build air
    - name: Build samples/custom-programmatic-skin
      working-directory: samples/custom-programmatic-skin
      run: |
        haxelib run openfl build air
    - name: Build samples/custom-programmatic-skin-with-states
      working-directory: samples/custom-programmatic-skin-with-states
      run: |
        haxelib run openfl build air
    - name: Build samples/custom-theme
      working-directory: samples/custom-theme
      run: |
        haxelib run openfl build air
    - name: Build samples/dark-mode
      working-directory: samples/dark-mode
      run: |
        haxelib run openfl build air
    - name: Build samples/hello-world
      working-directory: samples/hello-world
      run: |
        haxelib run openfl build air
    - name: Build samples/hn-reader
      working-directory: samples/hn-reader
      run: |
        haxelib run openfl build air
    - name: Build samples/horizontal-layout-percentage-sizing
      working-directory: samples/horizontal-layout-percentage-sizing
      run: |
        haxelib run openfl build air
    - name: Build samples/list-view-data-provider-collection-sorting
      working-directory: samples/list-view-data-provider-collection-sorting
      run: |
        haxelib run openfl build air
    - name: Build samples/login-form
      working-directory: samples/login-form
      run: |
        haxelib run openfl build air
    - name: Build samples/magic-8-ball-chat
      working-directory: samples/magic-8-ball-chat
      run: |
        haxelib run openfl build air
    - name: Build samples/router-navigator-pass-data-between-views
      working-directory: samples/router-navigator-pass-data-between-views
      run: |
        haxelib run openfl build air
    - name: Build samples/router-navigator-save-and-restore
      working-directory: samples/router-navigator-save-and-restore
      run: |
        haxelib run openfl build air
    - name: Build samples/stack-navigator-pass-data-between-views
      working-directory: samples/stack-navigator-pass-data-between-views
      run: |
        haxelib run openfl build air
    - name: Build samples/stack-navigator-save-and-restore
      working-directory: samples/stack-navigator-save-and-restore
      run: |
        haxelib run openfl build air
    - name: Build samples/tab-navigator
      working-directory: samples/tab-navigator
      run: |
        haxelib run openfl build air
    - name: Build samples/todomvc
      working-directory: samples/todomvc
      run: |
        haxelib run openfl build air